---
apiVersion: v1
kind: Service
metadata:
  name: btan9967-redis-service
  labels:
    username: btan9967
spec:
  type: ClusterIP
  selector:
    username: btan9967
    app: btan9967-redis
  ports:
  - name: btan9967-redis
    port: 6379
    targetPort: 6379
