---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btan9967-redis-pvc
  labels:
    username: btan9967
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
