---
version: "3"

services:
    gen-anim:
        image: benjamintan1/json-parser:1.0
        volumes:
            - ./test:/data
        user: "861303:821716"
        command: generate_animals.py /data/animals.json
    read-anim:
        image: benjamintan1/json-parser:1.0
        volumes:
            - ./test:/data
        user: "861303:821716"
        command: read_animals.py /data/animals.json
...                
