---
apiVersion: v1
kind: Service
metadata:
  name: btan9967-final-redis-service
  labels:
    username: btan9967
    env: final
spec:
  type: ClusterIP
# clusterIP: 10.101.199.157
  selector:
    app: btan9967-final-redis
  ports:
  - name: btan9967-final-redis
    port: 6379
    targetPort: 6379
