---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btan9967-final-redis-pvc
  labels:
    env: final
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
