---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btan9967-test-data
  labels:
    username: btan9967
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
