---
apiVersion: v1
kind: Service
metadata:
  name: btan9967-test-flask
  labels:
    username: btan9967
    env: test
spec:
  type: ClusterIP
  selector:
    app: btan9967-test-flask
  ports:
  - name: btan9967-test-flask
    port: 5000
    targetPort: 5000
