---
apiVersion: v1
kind: Service
metadata:
  name: btan9967-test-service
  labels:
    username: btan9967
    env: test
spec:
  type: ClusterIP
  selector:
    app: btan9967-test-redis
  ports:
  - name: btan9967-test-service
    port: 6379
    targetPort: 6379
