---
apiVersion: v1
kind: Service
metadata:
  name: btan9967-final-flask-service
  labels:
    env: test
    app: btan9967-final-flask
spec:
  type: ClusterIP
  selector:
    app: btan9967-final-flask
  ports:
  - name: flask-port
    port: 5000
    targetPort: 5000
