---
apiVersion: v1
kind: Service
metadata:
  name: btan9967-final-flask-service
  labels:
    username: btan9967
    env: test
spec:
  type: ClusterIP
  selector:
    username: btan9967
    app: btan9967-final-flask
  ports:
  - name: btan9967-flask
    port: 5000
    targetPort: 5000
